export const USER_REQUESTED = "USER_REQUESTED";
export const USER_LOADED = "USER_LOADED";

export const AUTH_ERROR = "AUTH_ERRORS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";